name: Scans

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

  schedule:
  - cron: "0 2 * * 1"

permissions:
  contents: read

jobs:

  mend:
    name: Mend Dependency Scan
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          if [ -f dev-requirements.txt ]; then
            pip install -r dev-requirements.txt
          fi

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Download Mend Unified Agent
        run: |
          curl -L -o wss-unified-agent.jar https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar

      - name: Get Mend Config and run agent
        env:
          WS_APIKEY: ${{ secrets.WS_APIKEY }}
          WS_WSS_URL: ${{ secrets.WS_WSS_URL }}
          WS_USERKEY: ${{ secrets.WS_USERKEY }}
          WS_PRODUCTNAME: ${{ secrets.WS_PRODUCTNAME }}
          WS_PROJECTNAME: ${{ secrets. WS_PROJECTNAME }}
        run: |
          java -jar wss-unified-agent.jar -d .

      - name: Upload Mend scan report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mend-scan-report
          path: |
            **/whitesource*
            **/mend*
          if-no-files-found: ignore

  pylint-scan:
    name: Pylint Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -e .
          if [ -f dev-requirements.txt ]; then
            pip install -r dev-requirements.txt
          fi

      - name: Run Pylint
        run: |
          pylint db2_sqlglot/ --output-format=json > pylint-report.json || true
          pylint db2_sqlglot/ || true

      - name: Upload Pylint Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pylint-quality-report
          path: pylint-report.json

  bandit-scan:
    name: Bandit Security Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install bandit
           pip install pylint
          pip install -e .
          if [ -f dev-requirements.txt ]; then
            pip install -r dev-requirements.txt
          fi

      - name: Run Bandit
        run: |
          bandit -r db2_sqlglot \
            -f json \
            -o bandit-report.json || true

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bandit-security-report
          path: bandit-report.json
